# Generated by Django 5.1.4 on 2024-12-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_field',
            new_name='image',
        ),
    ]
